### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by Isjacrod** [Isjacrod/aluracord-matrix#1]
- [ ] Adicionar meio de apagar mensagens
- [ ] Autenticar usuario principal
- [ ] Redimensinar stickers  para móvel e desktop
- [ ] Adicionar tema
